version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
             connector: postgres
            host: ec2-3-231-69-204.compute-1.amazonaws.com
            port: '5432'
            database: d6c2k7e6aeuo6f
            ssl: true
            user: bmjkuqjrwioeaq
            password: c34cdd99f40de4f382dd5e3e03aa5d42f6a88d790712463ae876172e8ecc26c1
            migrations: true
